import React, { useState } from 'react';
import { X, FileText, Download, Printer, Copy, Check } from 'lucide-react';
import { useChat } from '../../context/ChatContext';

export default function ExportModal({ isOpen, onClose }) {
  const { messages, currentChat } = useChat();
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const chatTitle = currentChat?.title || 'SmartAssist_Conversation';

  const generateMarkdown = () => {
    let md = `# ${chatTitle}\nGenerated by SmartAssist AI on ${new Date().toLocaleString()}\n\n---\n\n`;
    messages.forEach(msg => {
      const sender = msg.role === 'ai' ? '### 🤖 SmartAssist AI' : '### 👤 Student';
      const category = msg.category ? ` *[Category: ${msg.category}]*` : '';
      md += `${sender}${category}\n\n${msg.content}\n\n---\n\n`;
    });
    return md;
  };

  const generatePlainText = () => {
    let txt = `====================================================\n${chatTitle}\nSmartAssist AI - ${new Date().toLocaleString()}\n====================================================\n\n`;
    messages.forEach(msg => {
      const sender = msg.role === 'ai' ? 'SmartAssist AI' : 'Student';
      txt += `[${sender}]:\n${msg.content}\n\n----------------------------------------------------\n\n`;
    });
    return txt;
  };

  const handleDownload = (content, filename, type) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    onClose();
  };

  const handlePrintPdf = () => {
    window.print();
    onClose();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdown());
      setCopied(true);
      setTimeout(() => {
        setCopied(false);
        onClose();
      }, 1500);
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-md bg-white dark:bg-slate-900 rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 p-6 sm:p-8">
        <button
          onClick={onClose}
          className="absolute top-5 right-5 p-2 rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center space-x-3 mb-6">
          <div className="p-2.5 rounded-xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400">
            <Download className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-slate-900 dark:text-white">Export Conversation</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">Save notes, formulas, and code offline</p>
          </div>
        </div>

        <div className="space-y-3">
          <button
            onClick={handlePrintPdf}
            className="w-full flex items-center justify-between p-3.5 rounded-2xl border border-slate-200 dark:border-slate-800 hover:border-indigo-500 dark:hover:border-indigo-500 bg-slate-50 dark:bg-slate-800/40 hover:bg-indigo-50/30 dark:hover:bg-indigo-950/20 transition group text-left"
          >
            <div className="flex items-center space-x-3">
              <Printer className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              <div>
                <p className="text-xs font-semibold text-slate-900 dark:text-white">Print or Save as PDF</p>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">Uses browser print dialog with print styling</p>
              </div>
            </div>
          </button>

          <button
            onClick={() => handleDownload(generateMarkdown(), `${chatTitle.replace(/\s+/g, '_')}.md`, 'text/markdown')}
            className="w-full flex items-center justify-between p-3.5 rounded-2xl border border-slate-200 dark:border-slate-800 hover:border-indigo-500 dark:hover:border-indigo-500 bg-slate-50 dark:bg-slate-800/40 hover:bg-indigo-50/30 dark:hover:bg-indigo-950/20 transition group text-left"
          >
            <div className="flex items-center space-x-3">
              <FileText className="w-5 h-5 text-purple-600 dark:text-purple-400" />
              <div>
                <p className="text-xs font-semibold text-slate-900 dark:text-white">Download Markdown (.md)</p>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">Formatted with headers and code blocks</p>
              </div>
            </div>
          </button>

          <button
            onClick={() => handleDownload(generatePlainText(), `${chatTitle.replace(/\s+/g, '_')}.txt`, 'text/plain')}
            className="w-full flex items-center justify-between p-3.5 rounded-2xl border border-slate-200 dark:border-slate-800 hover:border-indigo-500 dark:hover:border-indigo-500 bg-slate-50 dark:bg-slate-800/40 hover:bg-indigo-50/30 dark:hover:bg-indigo-950/20 transition group text-left"
          >
            <div className="flex items-center space-x-3">
              <FileText className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
              <div>
                <p className="text-xs font-semibold text-slate-900 dark:text-white">Download Plain Text (.txt)</p>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">Lightweight clean ASCII format</p>
              </div>
            </div>
          </button>

          <button
            onClick={handleCopy}
            className="w-full flex items-center justify-between p-3.5 rounded-2xl border border-slate-200 dark:border-slate-800 hover:border-indigo-500 dark:hover:border-indigo-500 bg-slate-50 dark:bg-slate-800/40 hover:bg-indigo-50/30 dark:hover:bg-indigo-950/20 transition group text-left"
          >
            <div className="flex items-center space-x-3">
              {copied ? (
                <Check className="w-5 h-5 text-emerald-500" />
              ) : (
                <Copy className="w-5 h-5 text-slate-600 dark:text-slate-400" />
              )}
              <div>
                <p className="text-xs font-semibold text-slate-900 dark:text-white">
                  {copied ? 'Copied to Clipboard!' : 'Copy to Clipboard'}
                </p>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">Copy full chat markdown to clipboard</p>
              </div>
            </div>
          </button>
        </div>
      </div>
    </div>
  );
}
